name: Build
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      # this clones the repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android release
          workdir: .
          buildozer_version: stable

      - name: Prepare Changelog
        run: |
          echo 'CHNGLG<<EOF' >> $GITHUB_ENV
          cat /home/runner/work/android-app/android-app/changelog.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
      - name: Generate release tag
        id: tag
        # this gets the apk and extracts the version from the file name
        run: |
          echo "::set-output name=release_tag::$(ls bin | grep .apk | awk -F'[-]' '{print $2}')"
          
      - name: Rename apk file
        run: sudo mv ${{ steps.buildozer.outputs.filename }} bin/release.apk
        
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: ${{ github.event.head_commit.message }}
          body: |
            Changes since the last release:
            ${{ env.CHNGLG }}
          files: "${GITHUB_WORKSPACE}/release.apk"
