name: Build
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Diff/Changelog
        run: |
          echo 'DIFF<<EOF' >> $GITHUB_ENV
          git diff HEAD^..HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::AndroidRelease$(date +"%Y.%m.%d_%H-%M")"
          
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android release
          workdir: .
          buildozer_version: stable
          
      - name: Rename apk file
        run: cp ${{ steps.buildozer.outputs.filename }} bin/release.apk
        
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: ${{ github.event.head_commit.message }}
          body: |
            Changes since the last release:
            ```
            ${{ env.DIFF }}
            ```
          files: bin/release.apk
